import { ThemeName, ThemeRepository } from './model.ts'

export const themeRepository: Record<ThemeName, ThemeRepository> = {
  sysAdminDefault: {
    '--custom-background-color': 'none',
    '--window-radius': '2px',
    '--window-bg-color': '#121212',
    '--window-border-color': '#52525b',
    '--window-border-style': 'solid',
    '--window-border-thickness': '1px',

    '--window-navhandle-bg-color': '#262626',
    '--window-navhandle-tabs-text-color': '#f4f4f5',

    '--navbar-bg-color': '#18181b',
    '--navbar-opacity': '100%',
    '--navbar-justify': 'space-between',
    '--navbar-tabs-gap': '0px',

    '--window-navhandle-tabs-bg-color': '#18181b ',
    '--window-navhandle-title-color': 'white',

    '--navbar-window-button-bg': '#18181b',
    '--navbar-window-button-color': '#a1a1aa',
    '--navbar-window-button-font-size': '0.75rem',
    '--navbar-window-button-line-height': '1rem',
    '--navbar-window-button-height': '2.25rem',
    '--navbar-window-button-padding-inline': '8px',
    '--navbar-window-button-radius': '0',
    '--navbar-window-button-border-top-width': '0',
    '--navbar-window-button-border-right-width': '0',
    '--navbar-window-button-border-bottom-width': '0',
    '--navbar-window-button-border-left-width': '0',
    '--navbar-window-button-border-top-style': 'solid',
    '--navbar-window-button-border-right-style': 'solid',
    '--navbar-window-button-border-bottom-style': 'solid',
    '--navbar-window-button-border-left-style': 'solid',
    '--navbar-window-button-border-top-color': 'none',
    '--navbar-window-button-border-right-color': 'none',
    '--navbar-window-button-border-bottom-color': 'none',
    '--navbar-window-button-border-left-color': 'none',

    '--navbar-settings-button-color': '#f4f4f5',

    '--desktop-window-icon-color': '#f4f4f5',
    '--desktop-window-icon-width': 'fit-content',
    '--desktop-window-icon-padding': '1rem',
    '--desktop-window-icon-border-radius': '0',
    '--desktop-window-icon-background': 'rgb(82 82 91 / 0.5)',
    '--desktop-window-icon-border-top-width': '0',
    '--desktop-window-icon-border-right-width': '0',
    '--desktop-window-icon-border-bottom-width': '0',
    '--desktop-window-icon-border-left-width': '0',
    '--desktop-window-icon-border-top-style': 'solid',
    '--desktop-window-icon-border-right-style': 'solid',
    '--desktop-window-icon-border-bottom-style': 'solid',
    '--desktop-window-icon-border-left-style': 'solid',
    '--desktop-window-icon-border-top-color': 'transparent',
    '--desktop-window-icon-border-right-color': 'transparent',
    '--desktop-window-icon-border-bottom-color': '#a1a1aa',
    '--desktop-window-icon-border-left-color': 'transparent',

    '--text-primary-color': 'white',
    '--text-primary-font-family': 'Arial',
  },

  blackhat: {
    '--custom-background-color': 'none',
    '--window-radius': '0',
    '--window-bg-color': 'rgb(0 8 4 / 0.92)',
    '--window-border-color': '#16a34a',
    '--window-border-style': 'solid',
    '--window-border-thickness': '1px',

    '--window-navhandle-bg-color': '#001b0c',
    '--window-navhandle-tabs-text-color': '#86efac',

    '--navbar-bg-color': '#000804',
    '--navbar-opacity': '100%',
    '--navbar-justify': 'end',
    '--navbar-tabs-gap': '0px',

    '--window-navhandle-tabs-bg-color': '#001407',
    '--window-navhandle-title-color': '#86efac',

    '--navbar-window-button-bg': '#001407',
    '--navbar-window-button-color': '#4ade80',
    '--navbar-window-button-font-size': '0.75rem',
    '--navbar-window-button-line-height': '1rem',
    '--navbar-window-button-height': '2rem',
    '--navbar-window-button-padding-inline': '8px',
    '--navbar-window-button-radius': '0',
    '--navbar-window-button-border-top-width': '1px',
    '--navbar-window-button-border-right-width': '1px',
    '--navbar-window-button-border-bottom-width': '1px',
    '--navbar-window-button-border-left-width': '1px',
    '--navbar-window-button-border-top-style': 'solid',
    '--navbar-window-button-border-right-style': 'solid',
    '--navbar-window-button-border-bottom-style': 'solid',
    '--navbar-window-button-border-left-style': 'solid',
    '--navbar-window-button-border-top-color': '#14532d',
    '--navbar-window-button-border-right-color': '#14532d',
    '--navbar-window-button-border-bottom-color': '#22c55e',
    '--navbar-window-button-border-left-color': '#14532d',

    '--navbar-settings-button-color': '#86efac',

    '--desktop-window-icon-color': '#86efac',
    '--desktop-window-icon-width': 'fit-content',
    '--desktop-window-icon-padding': '0.875rem',
    '--desktop-window-icon-border-radius': '0',
    '--desktop-window-icon-background': 'rgb(0 20 7 / 0.72)',
    '--desktop-window-icon-border-top-width': '1px',
    '--desktop-window-icon-border-right-width': '1px',
    '--desktop-window-icon-border-bottom-width': '1px',
    '--desktop-window-icon-border-left-width': '1px',
    '--desktop-window-icon-border-top-style': 'solid',
    '--desktop-window-icon-border-right-style': 'solid',
    '--desktop-window-icon-border-bottom-style': 'solid',
    '--desktop-window-icon-border-left-style': 'solid',
    '--desktop-window-icon-border-top-color': '#14532d',
    '--desktop-window-icon-border-right-color': '#14532d',
    '--desktop-window-icon-border-bottom-color': '#22c55e',
    '--desktop-window-icon-border-left-color': '#14532d',

    '--text-primary-color': '#86efac',
    '--text-primary-font-family': 'monospace',
  },

  retro: {
    '--custom-background-color': 'none',
    '--window-radius': '0',
    '--window-bg-color': '#fffef5',
    '--window-border-color': '#3f3f46',
    '--window-border-style': 'solid',
    '--window-border-thickness': '2px',

    '--window-navhandle-bg-color': '#888888',
    '--window-navhandle-title-color': '#18181b',

    '--navbar-bg-color': '#dddddd',
    '--navbar-opacity': '100%',
    '--navbar-justify': 'space-between',
    '--navbar-tabs-gap': '0.375rem',

    '--window-navhandle-tabs-bg-color': '#eeeeee',
    '--window-navhandle-tabs-text-color': 'black',

    '--navbar-window-button-bg': '#999999',
    '--navbar-window-button-color': '#18181b',
    '--navbar-window-button-font-size': '0.75rem',
    '--navbar-window-button-line-height': '1rem',
    '--navbar-window-button-height': '2rem',
    '--navbar-window-button-padding-inline': '8px',
    '--navbar-window-button-radius': '0',
    '--navbar-window-button-border-top-width': '2px',
    '--navbar-window-button-border-right-width': '2px',
    '--navbar-window-button-border-bottom-width': '3px',
    '--navbar-window-button-border-left-width': '2px',
    '--navbar-window-button-border-top-style': 'solid',
    '--navbar-window-button-border-right-style': 'solid',
    '--navbar-window-button-border-bottom-style': 'solid',
    '--navbar-window-button-border-left-style': 'solid',
    '--navbar-window-button-border-top-color': '#a1a1aa',
    '--navbar-window-button-border-right-color': '#27272a',
    '--navbar-window-button-border-bottom-color': '#18181b',
    '--navbar-window-button-border-left-color': '#a1a1aa',

    '--navbar-settings-button-color': '#27272a',

    '--desktop-window-icon-color': '#18181b',
    '--desktop-window-icon-width': 'fit-content',
    '--desktop-window-icon-padding': '1rem',
    '--desktop-window-icon-border-radius': '0',
    '--desktop-window-icon-background': 'rgb(241 240 232 / 0.72)',
    '--desktop-window-icon-border-top-width': '2px',
    '--desktop-window-icon-border-right-width': '2px',
    '--desktop-window-icon-border-bottom-width': '3px',
    '--desktop-window-icon-border-left-width': '2px',
    '--desktop-window-icon-border-top-style': 'solid',
    '--desktop-window-icon-border-right-style': 'solid',
    '--desktop-window-icon-border-bottom-style': 'solid',
    '--desktop-window-icon-border-left-style': 'solid',
    '--desktop-window-icon-border-top-color': '#ffffff',
    '--desktop-window-icon-border-right-color': '#78716c',
    '--desktop-window-icon-border-bottom-color': '#44403c',
    '--desktop-window-icon-border-left-color': '#ffffff',

    '--text-primary-color': 'black',
    '--text-primary-font-family': '"Trebuchet MS", "Tahoma", "Verdana", Arial, sans-serif',
  },

  brutalist: {
    '--custom-background-color': 'none',
    '--window-radius': '2px 12px 4px 9px',
    '--window-bg-color': '#ffea00',
    '--window-border-color': '#050505',
    '--window-border-style': 'solid',
    '--window-border-thickness': '3px',

    '--window-navhandle-bg-color': 'black',
    '--window-navhandle-title-color': 'white',
    '--window-navhandle-tabs-bg-color': 'white',
    '--window-navhandle-tabs-text-color': 'black',

    '--navbar-bg-color': '#f5f5f0',
    '--navbar-opacity': '100%',
    '--navbar-justify': 'space-between',
    '--navbar-tabs-gap': '0.375rem',

    '--navbar-window-button-bg': '#f5f5f0',
    '--navbar-window-button-color': '#050505',
    '--navbar-window-button-font-size': '0.75rem',
    '--navbar-window-button-line-height': '1rem',
    '--navbar-window-button-height': '2.25rem',
    '--navbar-window-button-padding-inline': '10px',
    '--navbar-window-button-radius': '2px 7px 1px 5px',
    '--navbar-window-button-border-top-width': '2px',
    '--navbar-window-button-border-right-width': '4px',
    '--navbar-window-button-border-bottom-width': '3px',
    '--navbar-window-button-border-left-width': '2px',
    '--navbar-window-button-border-top-style': 'solid',
    '--navbar-window-button-border-right-style': 'solid',
    '--navbar-window-button-border-bottom-style': 'solid',
    '--navbar-window-button-border-left-style': 'solid',
    '--navbar-window-button-border-top-color': '#050505',
    '--navbar-window-button-border-right-color': '#050505',
    '--navbar-window-button-border-bottom-color': '#050505',
    '--navbar-window-button-border-left-color': '#050505',

    '--navbar-settings-button-color': '#050505',

    '--desktop-window-icon-color': '#050505',
    '--desktop-window-icon-width': 'fit-content',
    '--desktop-window-icon-padding': '1rem',
    '--desktop-window-icon-border-radius': '1px 9px 3px 7px',
    '--desktop-window-icon-background': '#f5f5f0',
    '--desktop-window-icon-border-top-width': '2px',
    '--desktop-window-icon-border-right-width': '4px',
    '--desktop-window-icon-border-bottom-width': '3px',
    '--desktop-window-icon-border-left-width': '2px',
    '--desktop-window-icon-border-top-style': 'solid',
    '--desktop-window-icon-border-right-style': 'solid',
    '--desktop-window-icon-border-bottom-style': 'solid',
    '--desktop-window-icon-border-left-style': 'solid',
    '--desktop-window-icon-border-top-color': '#050505',
    '--desktop-window-icon-border-right-color': '#050505',
    '--desktop-window-icon-border-bottom-color': '#050505',
    '--desktop-window-icon-border-left-color': '#050505',

    '--text-primary-color': '#050505',
    '--text-primary-font-family': 'cursive',
  },
} as const
