import { ThemeName, ThemeRepository } from './model.ts'

export const themeRepository: Record<ThemeName, ThemeRepository> = {
  sysAdminDefault: {
    '--window-radius': '2px',
    '--window-bg-color': 'white',
    '--window-border-color': '#52525b',
    '--window-border-style': 'solid',
    '--window-border-thickness': '1px',

    '--window-navhandle-bg-color': '#262626',
    '--window-navhandle-title-color': 'white',

    '--navbar-bg-color': '#18181b',
    '--navbar-opacity': '10%',
    '--navbar-justify': 'space-between',
    '--navbar-tabs-gap': '0px',

    '--window-navhandle-tabs-bg-color': '#18181b ',

    '--navbar-window-button-bg': '#18181b',
    '--navbar-window-button-color': '#a1a1aa',
    '--navbar-window-button-font-size': '0.75rem',
    '--navbar-window-button-line-height': '1rem',
    '--navbar-window-button-height': '2.25rem',
    '--navbar-window-button-padding-inline': '1rem',
    '--navbar-window-button-radius': '0',
    '--navbar-window-button-border-top-width': '',
    '--navbar-window-button-border-right-width': '',
    '--navbar-window-button-border-bottom-width': '',
    '--navbar-window-button-border-left-width': '',
    '--navbar-window-button-border-top-style': '',
    '--navbar-window-button-border-right-style': '',
    '--navbar-window-button-border-bottom-style': '',
    '--navbar-window-button-border-left-style': '',
    '--navbar-window-button-border-top-color': '',
    '--navbar-window-button-border-right-color': '',
    '--navbar-window-button-border-bottom-color': '',
    '--navbar-window-button-border-left-color': '',

    '--navbar-settings-button-color': '#f4f4f5',

    '--desktop-window-icon-color': '#f4f4f5',
    '--desktop-window-icon-width': 'fit-content',
    '--desktop-window-icon-padding': '1rem',
    '--desktop-window-icon-border-radius': '0',
    '--desktop-window-icon-background': 'rgb(82 82 91 / 0.5)',
    '--desktop-window-icon-border-top-width': '0',
    '--desktop-window-icon-border-right-width': '0',
    '--desktop-window-icon-border-bottom-width': '0',
    '--desktop-window-icon-border-left-width': '0',
    '--desktop-window-icon-border-top-style': 'solid',
    '--desktop-window-icon-border-right-style': 'solid',
    '--desktop-window-icon-border-bottom-style': 'solid',
    '--desktop-window-icon-border-left-style': 'solid',
    '--desktop-window-icon-border-top-color': 'transparent',
    '--desktop-window-icon-border-right-color': 'transparent',
    '--desktop-window-icon-border-bottom-color': '#a1a1aa',
    '--desktop-window-icon-border-left-color': 'transparent',

    '--text-primary-color': '#f4f4f5',
    '--text-primary-font-family': 'monospace',
  },

  clinic: {
    '--window-radius': '8px',
    '--window-bg-color': '#f8fafc99',
    '--window-border-color': '#bae6fd',
    '--window-border-style': 'solid',
    '--window-border-thickness': '1px',

    '--window-navhandle-bg-color': '#e0f2fe',
    '--window-navhandle-title-color': '#0c4a6e',

    '--navbar-bg-color': '#ffffff10',
    '--navbar-opacity': '100%',
    '--navbar-justify': 'space-between',
    '--navbar-tabs-gap': '0.5rem',

    '--window-navhandle-tabs-bg-color': '#ffffff',

    '--navbar-window-button-bg': '#EEEEEE20',
    '--navbar-window-button-color': '#444444',
    '--navbar-window-button-font-size': '0.75rem',
    '--navbar-window-button-line-height': '1rem',
    '--navbar-window-button-height': '2rem',
    '--navbar-window-button-padding-inline': '1rem',
    '--navbar-window-button-radius': '4px',
    '--navbar-window-button-border-top-width': '1px',
    '--navbar-window-button-border-right-width': '1px',
    '--navbar-window-button-border-bottom-width': '3px',
    '--navbar-window-button-border-left-width': '1px',
    '--navbar-window-button-border-top-style': 'solid',
    '--navbar-window-button-border-right-style': 'solid',
    '--navbar-window-button-border-bottom-style': 'solid',
    '--navbar-window-button-border-left-style': 'solid',
    '--navbar-window-button-border-top-color': '#bae6fd',
    '--navbar-window-button-border-right-color': '#bae6fd',
    '--navbar-window-button-border-bottom-color': '#38bdf8',
    '--navbar-window-button-border-left-color': '#bae6fd',

    '--navbar-settings-button-color': '#0284c7',

    '--desktop-window-icon-color': '#075985',
    '--desktop-window-icon-width': 'fit-content',
    '--desktop-window-icon-padding': '1rem',
    '--desktop-window-icon-border-radius': '1rem',
    '--desktop-window-icon-background': 'rgb(224 242 254 / 0.2)',
    '--desktop-window-icon-border-top-width': '1px',
    '--desktop-window-icon-border-right-width': '1px',
    '--desktop-window-icon-border-bottom-width': '3px',
    '--desktop-window-icon-border-left-width': '1px',
    '--desktop-window-icon-border-top-style': 'solid',
    '--desktop-window-icon-border-right-style': 'solid',
    '--desktop-window-icon-border-bottom-style': 'solid',
    '--desktop-window-icon-border-left-style': 'solid',
    '--desktop-window-icon-border-top-color': '#bae6fd',
    '--desktop-window-icon-border-right-color': '#bae6fd',
    '--desktop-window-icon-border-bottom-color': '#38bdf8',
    '--desktop-window-icon-border-left-color': '#bae6fd',

    '--text-primary-color': '#0f172a',
    '--text-primary-font-family': '"Inter", "Segoe UI", Arial, Helvetica, sans-serif',
  },

  zen: {
    '--window-radius': '6px',
    '--window-bg-color': 'rgb(250 248 241 / 0.88)',
    '--window-border-color': '#d7c7a3',
    '--window-border-style': 'solid',
    '--window-border-thickness': '1px',

    '--window-navhandle-bg-color': '#e9ddc5',
    '--window-navhandle-title-color': '#28382b',

    '--navbar-bg-color': '#f4ead5',
    '--navbar-opacity': '96%',
    '--navbar-justify': 'space-between',
    '--navbar-tabs-gap': '0.375rem',

    '--window-navhandle-tabs-bg-color': '#e9ddc580',

    '--navbar-window-button-bg': '#ffedd550',
    '--navbar-window-button-color': '#304236',
    '--navbar-window-button-font-size': '0.75rem',
    '--navbar-window-button-line-height': '1rem',
    '--navbar-window-button-height': '2rem',
    '--navbar-window-button-padding-inline': '1rem',
    '--navbar-window-button-radius': '999px',
    '--navbar-window-button-border-top-width': '1px',
    '--navbar-window-button-border-right-width': '1px',
    '--navbar-window-button-border-bottom-width': '2px',
    '--navbar-window-button-border-left-width': '1px',
    '--navbar-window-button-border-top-style': 'solid',
    '--navbar-window-button-border-right-style': 'solid',
    '--navbar-window-button-border-bottom-style': 'solid',
    '--navbar-window-button-border-left-style': 'solid',
    '--navbar-window-button-border-top-color': '#ded0b4',
    '--navbar-window-button-border-right-color': '#ded0b4',
    '--navbar-window-button-border-bottom-color': '#8b9d77',
    '--navbar-window-button-border-left-color': '#ded0b4',

    '--navbar-settings-button-color': '#4d6a54',

    '--desktop-window-icon-color': '#25362a',
    '--desktop-window-icon-width': 'fit-content',
    '--desktop-window-icon-padding': '1rem',
    '--desktop-window-icon-border-radius': '999px',
    '--desktop-window-icon-background': 'rgb(255 252 245 / 0.58)',
    '--desktop-window-icon-border-top-width': '1px',
    '--desktop-window-icon-border-right-width': '1px',
    '--desktop-window-icon-border-bottom-width': '2px',
    '--desktop-window-icon-border-left-width': '1px',
    '--desktop-window-icon-border-top-style': 'solid',
    '--desktop-window-icon-border-right-style': 'solid',
    '--desktop-window-icon-border-bottom-style': 'solid',
    '--desktop-window-icon-border-left-style': 'solid',
    '--desktop-window-icon-border-top-color': '#ded0b4',
    '--desktop-window-icon-border-right-color': '#ded0b4',
    '--desktop-window-icon-border-bottom-color': '#8b9d77',
    '--desktop-window-icon-border-left-color': '#ded0b4',

    '--text-primary-color': '#25362a',
    '--text-primary-font-family': '"Inter", "Segoe UI", Arial, Helvetica, sans-serif',
  },

  cyberpunkNeon: {
    '--window-radius': '4px',
    '--window-bg-color': 'rgb(9 12 27 / 0.86)',
    '--window-border-color': '#00f5ff',
    '--window-border-style': 'solid',
    '--window-border-thickness': '1px',

    '--window-navhandle-bg-color': '#080a19',
    '--window-navhandle-title-color': '#f0f7ff',

    '--navbar-bg-color': '#070816',
    '--navbar-opacity': '98%',
    '--navbar-justify': 'space-between',
    '--navbar-tabs-gap': '0.375rem',

    '--window-navhandle-tabs-bg-color': '#121633',

    '--navbar-window-button-bg': 'rgb(16 20 47 / 0.86)',
    '--navbar-window-button-color': '#67e8f9',
    '--navbar-window-button-font-size': '0.75rem',
    '--navbar-window-button-line-height': '1rem',
    '--navbar-window-button-height': '2rem',
    '--navbar-window-button-padding-inline': '1rem',
    '--navbar-window-button-radius': '2px',
    '--navbar-window-button-border-top-width': '1px',
    '--navbar-window-button-border-right-width': '1px',
    '--navbar-window-button-border-bottom-width': '2px',
    '--navbar-window-button-border-left-width': '1px',
    '--navbar-window-button-border-top-style': 'solid',
    '--navbar-window-button-border-right-style': 'solid',
    '--navbar-window-button-border-bottom-style': 'solid',
    '--navbar-window-button-border-left-style': 'solid',
    '--navbar-window-button-border-top-color': '#22d3ee',
    '--navbar-window-button-border-right-color': '#a855f7',
    '--navbar-window-button-border-bottom-color': '#f0abfc',
    '--navbar-window-button-border-left-color': '#22d3ee',

    '--navbar-settings-button-color': '#f0abfc',

    '--desktop-window-icon-color': '#e0faff',
    '--desktop-window-icon-width': 'fit-content',
    '--desktop-window-icon-padding': '1rem',
    '--desktop-window-icon-border-radius': '2px',
    '--desktop-window-icon-background': 'rgb(13 17 38 / 0.66)',
    '--desktop-window-icon-border-top-width': '1px',
    '--desktop-window-icon-border-right-width': '1px',
    '--desktop-window-icon-border-bottom-width': '2px',
    '--desktop-window-icon-border-left-width': '1px',
    '--desktop-window-icon-border-top-style': 'solid',
    '--desktop-window-icon-border-right-style': 'solid',
    '--desktop-window-icon-border-bottom-style': 'solid',
    '--desktop-window-icon-border-left-style': 'solid',
    '--desktop-window-icon-border-top-color': '#22d3ee',
    '--desktop-window-icon-border-right-color': '#a855f7',
    '--desktop-window-icon-border-bottom-color': '#f0abfc',
    '--desktop-window-icon-border-left-color': '#22d3ee',

    '--text-primary-color': '#e0faff',
    '--text-primary-font-family': 'monospace',
  },

  blackhat: {
    '--window-radius': '0',
    '--window-bg-color': 'rgb(0 8 4 / 0.92)',
    '--window-border-color': '#16a34a',
    '--window-border-style': 'solid',
    '--window-border-thickness': '1px',

    '--window-navhandle-bg-color': '#001b0c',
    '--window-navhandle-title-color': '#86efac',

    '--navbar-bg-color': '#000804',
    '--navbar-opacity': '100%',
    '--navbar-justify': 'space-between',
    '--navbar-tabs-gap': '0px',

    '--window-navhandle-tabs-bg-color': '#001407',

    '--navbar-window-button-bg': '#001407',
    '--navbar-window-button-color': '#4ade80',
    '--navbar-window-button-font-size': '0.75rem',
    '--navbar-window-button-line-height': '1rem',
    '--navbar-window-button-height': '2rem',
    '--navbar-window-button-padding-inline': '0.875rem',
    '--navbar-window-button-radius': '0',
    '--navbar-window-button-border-top-width': '1px',
    '--navbar-window-button-border-right-width': '1px',
    '--navbar-window-button-border-bottom-width': '1px',
    '--navbar-window-button-border-left-width': '1px',
    '--navbar-window-button-border-top-style': 'solid',
    '--navbar-window-button-border-right-style': 'solid',
    '--navbar-window-button-border-bottom-style': 'solid',
    '--navbar-window-button-border-left-style': 'solid',
    '--navbar-window-button-border-top-color': '#14532d',
    '--navbar-window-button-border-right-color': '#14532d',
    '--navbar-window-button-border-bottom-color': '#22c55e',
    '--navbar-window-button-border-left-color': '#14532d',

    '--navbar-settings-button-color': '#86efac',

    '--desktop-window-icon-color': '#86efac',
    '--desktop-window-icon-width': 'fit-content',
    '--desktop-window-icon-padding': '0.875rem',
    '--desktop-window-icon-border-radius': '0',
    '--desktop-window-icon-background': 'rgb(0 20 7 / 0.72)',
    '--desktop-window-icon-border-top-width': '1px',
    '--desktop-window-icon-border-right-width': '1px',
    '--desktop-window-icon-border-bottom-width': '1px',
    '--desktop-window-icon-border-left-width': '1px',
    '--desktop-window-icon-border-top-style': 'solid',
    '--desktop-window-icon-border-right-style': 'solid',
    '--desktop-window-icon-border-bottom-style': 'solid',
    '--desktop-window-icon-border-left-style': 'solid',
    '--desktop-window-icon-border-top-color': '#14532d',
    '--desktop-window-icon-border-right-color': '#14532d',
    '--desktop-window-icon-border-bottom-color': '#22c55e',
    '--desktop-window-icon-border-left-color': '#14532d',

    '--text-primary-color': '#86efac',
    '--text-primary-font-family': 'monospace',
  },
} as const
