import { ThemeName, ThemeRepository } from './model.ts'

export const themeRepository: Record<ThemeName, ThemeRepository> = {
  sysAdminDefault: {
    '--window-radius': '2px',
    '--window-bg-color': 'white',
    '--window-border-color': '#52525b',
    '--window-border-style': 'solid',
    '--window-border-thickness': '1px',

    '--window-navhandle-bg-color': '#262626',
    '--window-navhandle-title-color': 'white',

    '--navbar-bg-color': '#18181b',
    '--navbar-opacity': '10%',
    '--navbar-justify': 'space-between',
    '--navbar-tabs-gap': '0px',

    '--window-navhandle-tabs-bg-color': '#18181b ',

    '--navbar-window-button-bg': '#18181b',
    '--navbar-window-button-color': '#a1a1aa',
    '--navbar-window-button-font-size': '0.75rem',
    '--navbar-window-button-line-height': '1rem',
    '--navbar-window-button-height': '2.25rem',
    '--navbar-window-button-padding-inline': '1rem',
    '--navbar-window-button-radius': '0',
    '--navbar-window-button-border-top-width': '',
    '--navbar-window-button-border-right-width': '',
    '--navbar-window-button-border-bottom-width': '',
    '--navbar-window-button-border-left-width': '',
    '--navbar-window-button-border-top-style': '',
    '--navbar-window-button-border-right-style': '',
    '--navbar-window-button-border-bottom-style': '',
    '--navbar-window-button-border-left-style': '',
    '--navbar-window-button-border-top-color': '',
    '--navbar-window-button-border-right-color': '',
    '--navbar-window-button-border-bottom-color': '',
    '--navbar-window-button-border-left-color': '',

    '--navbar-settings-button-color': '#f4f4f5',

    '--desktop-window-icon-color': '#f4f4f5',
    '--desktop-window-icon-width': 'fit-content',
    '--desktop-window-icon-padding': '1rem',
    '--desktop-window-icon-border-radius': '0',
    '--desktop-window-icon-background': 'rgb(82 82 91 / 0.5)',
    '--desktop-window-icon-border-top-width': '0',
    '--desktop-window-icon-border-right-width': '0',
    '--desktop-window-icon-border-bottom-width': '0',
    '--desktop-window-icon-border-left-width': '0',
    '--desktop-window-icon-border-top-style': 'solid',
    '--desktop-window-icon-border-right-style': 'solid',
    '--desktop-window-icon-border-bottom-style': 'solid',
    '--desktop-window-icon-border-left-style': 'solid',
    '--desktop-window-icon-border-top-color': 'transparent',
    '--desktop-window-icon-border-right-color': 'transparent',
    '--desktop-window-icon-border-bottom-color': '#a1a1aa',
    '--desktop-window-icon-border-left-color': 'transparent',

    '--text-primary-color': '#f4f4f5',
    '--text-primary-font-family': 'monospace',
  },

  blackhat: {
    '--window-radius': '0',
    '--window-bg-color': 'rgb(0 8 4 / 0.92)',
    '--window-border-color': '#16a34a',
    '--window-border-style': 'solid',
    '--window-border-thickness': '1px',

    '--window-navhandle-bg-color': '#001b0c',
    '--window-navhandle-title-color': '#86efac',

    '--navbar-bg-color': '#000804',
    '--navbar-opacity': '100%',
    '--navbar-justify': 'space-between',
    '--navbar-tabs-gap': '0px',

    '--window-navhandle-tabs-bg-color': '#001407',

    '--navbar-window-button-bg': '#001407',
    '--navbar-window-button-color': '#4ade80',
    '--navbar-window-button-font-size': '0.75rem',
    '--navbar-window-button-line-height': '1rem',
    '--navbar-window-button-height': '2rem',
    '--navbar-window-button-padding-inline': '0.875rem',
    '--navbar-window-button-radius': '0',
    '--navbar-window-button-border-top-width': '1px',
    '--navbar-window-button-border-right-width': '1px',
    '--navbar-window-button-border-bottom-width': '1px',
    '--navbar-window-button-border-left-width': '1px',
    '--navbar-window-button-border-top-style': 'solid',
    '--navbar-window-button-border-right-style': 'solid',
    '--navbar-window-button-border-bottom-style': 'solid',
    '--navbar-window-button-border-left-style': 'solid',
    '--navbar-window-button-border-top-color': '#14532d',
    '--navbar-window-button-border-right-color': '#14532d',
    '--navbar-window-button-border-bottom-color': '#22c55e',
    '--navbar-window-button-border-left-color': '#14532d',

    '--navbar-settings-button-color': '#86efac',

    '--desktop-window-icon-color': '#86efac',
    '--desktop-window-icon-width': 'fit-content',
    '--desktop-window-icon-padding': '0.875rem',
    '--desktop-window-icon-border-radius': '0',
    '--desktop-window-icon-background': 'rgb(0 20 7 / 0.72)',
    '--desktop-window-icon-border-top-width': '1px',
    '--desktop-window-icon-border-right-width': '1px',
    '--desktop-window-icon-border-bottom-width': '1px',
    '--desktop-window-icon-border-left-width': '1px',
    '--desktop-window-icon-border-top-style': 'solid',
    '--desktop-window-icon-border-right-style': 'solid',
    '--desktop-window-icon-border-bottom-style': 'solid',
    '--desktop-window-icon-border-left-style': 'solid',
    '--desktop-window-icon-border-top-color': '#14532d',
    '--desktop-window-icon-border-right-color': '#14532d',
    '--desktop-window-icon-border-bottom-color': '#22c55e',
    '--desktop-window-icon-border-left-color': '#14532d',

    '--text-primary-color': '#86efac',
    '--text-primary-font-family': 'monospace',
  },

  retro: {
    '--window-radius': '0',
    '--window-bg-color': '#f1f0e8',
    '--window-border-color': '#3f3f46',
    '--window-border-style': 'solid',
    '--window-border-thickness': '2px',

    '--window-navhandle-bg-color': '#777777',
    '--window-navhandle-title-color': '#f8fafc',

    '--navbar-bg-color': '#d8d6cc',
    '--navbar-opacity': '100%',
    '--navbar-justify': 'space-between',
    '--navbar-tabs-gap': '0.375rem',

    '--window-navhandle-tabs-bg-color': '#b8b6ad',

    '--navbar-window-button-bg': '#777777',
    '--navbar-window-button-color': '#f5f5f4',
    '--navbar-window-button-font-size': '0.75rem',
    '--navbar-window-button-line-height': '1rem',
    '--navbar-window-button-height': '2rem',
    '--navbar-window-button-padding-inline': '1rem',
    '--navbar-window-button-radius': '0',
    '--navbar-window-button-border-top-width': '2px',
    '--navbar-window-button-border-right-width': '2px',
    '--navbar-window-button-border-bottom-width': '3px',
    '--navbar-window-button-border-left-width': '2px',
    '--navbar-window-button-border-top-style': 'solid',
    '--navbar-window-button-border-right-style': 'solid',
    '--navbar-window-button-border-bottom-style': 'solid',
    '--navbar-window-button-border-left-style': 'solid',
    '--navbar-window-button-border-top-color': '#a1a1aa',
    '--navbar-window-button-border-right-color': '#27272a',
    '--navbar-window-button-border-bottom-color': '#18181b',
    '--navbar-window-button-border-left-color': '#a1a1aa',

    '--navbar-settings-button-color': '#27272a',

    '--desktop-window-icon-color': '#18181b',
    '--desktop-window-icon-width': 'fit-content',
    '--desktop-window-icon-padding': '1rem',
    '--desktop-window-icon-border-radius': '0',
    '--desktop-window-icon-background': 'rgb(241 240 232 / 0.72)',
    '--desktop-window-icon-border-top-width': '2px',
    '--desktop-window-icon-border-right-width': '2px',
    '--desktop-window-icon-border-bottom-width': '3px',
    '--desktop-window-icon-border-left-width': '2px',
    '--desktop-window-icon-border-top-style': 'solid',
    '--desktop-window-icon-border-right-style': 'solid',
    '--desktop-window-icon-border-bottom-style': 'solid',
    '--desktop-window-icon-border-left-style': 'solid',
    '--desktop-window-icon-border-top-color': '#ffffff',
    '--desktop-window-icon-border-right-color': '#78716c',
    '--desktop-window-icon-border-bottom-color': '#44403c',
    '--desktop-window-icon-border-left-color': '#ffffff',

    '--text-primary-color': '#18181b',
    '--text-primary-font-family': '"Trebuchet MS", "Tahoma", "Verdana", Arial, sans-serif',
  },
} as const
